#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages
sudo apt-get -y update
sudo apt-get -y install nginx
export HOSTNAME=$(hostname)
sudo sed -i '/location \/ {/ a add_header X-Served-By $HOSTNAME always;' /etc/nginx/sites-enabled/default
sudo service nginx start
