#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
# wget 35.196.255.60 &>/dev/null; 
# cat index.html | sudo tee /etc/haproxy/haproxy.cfg > /dev/null 2>&1
# rm *.html
echo "frontend leadering.tech
    bind *:80
    default_backend web_servers


backend web_servers
    balance roundrobin
    server 1565-web-02 35.227.13.42:80 check
    server 1565-web-01 35.196.255.60:80 check" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null 2>&1

sudo service haproxy reload
