#!/usr/bin/env bash
# Fix the script to improve the conection in port 80
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default 
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default 
sudo service nginx restart
