#!/usr/bin/env bash
# script that makes al lot of thinks

touch /var/run/holbertonscript.pid; echo "$$" > /var/run/holbertonscript.pid
while true; do
     echo "To infinity and beyond"
     sleep 2
     trap "echo I hate the kill command" SIGTERM
     trap "echo Y U no love me?!" SIGINT
     trap "{ sudo rm -rf /var/run/holbertonscript.pid; exit 0; }" SIGQUIT SIGTERM
done
