#!/usr/bin/env bash
# displays lines containing the bash word
# shellcheck disable=SC2009


ps aux -A --forest | while read a; do
     echo "------------------------------"
     echo "$a"
     echo "$a" | cut -d ' ' -f 30-
     echo "------------------------------"

done