#!/usr/bin/env bash
# that manages manage_my_process

if [ "$1" = "start" ]; then
     touch /var/run/my_process.pid
     echo "manage_my_process started"
elif [ "$1" = "stop" ]; then
     echo "manage_my_process stopped"
elif [ "$1" = "restart" ]; then
     echo "manage_my_process restarted"
else
     echo 'Usage: manage_my_process {start|stop|restart}'
fi