#!/usr/bin/env bash
# displays Holberton School 10 times, but for the 9th iteration
# displays Hi on a new line.
i=0
while [ $i -lt 11 ]
do
     if [ $i = 9 ]
     then
          echo "Hi"
     else
          echo "Holberton School"
     fi
:    $((i++))
done
