#!/usr/bin/env bash
# displays Holberton School 20 times, print different
i=1
while [ $i -le 20 ]
do
     echo "$i"
     if [ $i = 3 ]
     then
          echo "bad luck from China"
     elif [ $i = 9 ]
     then
          echo "bad luck from Japan"
     elif [ $i = 17 ]
     then
          echo "bad luck from Italy"
     fi
:    $(( i++ ))
done
