#!/usr/bin/env bash
# displays Holberton School 20 times, print different
i=1
while [ $i -le 20 ]; do
     echo "$i"
     case  $i in
          3)
          echo "bad luck from China"
     ;;
          9)
          echo "bad luck from Japan"
     ;;
          17)
          echo "bad luck from Italy"
     ;;
     esac
:    $(( i++ ))
done
