#!/usr/bin/env bash
# gives you information about the holbertonschool file

holb_file="holbertonschool"

if [ -e $holb_file ]
then
     echo "holbertonschool file exists"
     if [ -s $holb_file ]; then
          echo "holbertonschool file is not empty"
     else
          echo "holbertonschool file is empty"
     fi
     if [ -f $holb_file ]; then
          echo "holbertonschool is a regular file"
     fi
else
     echo "holbertonschool file does not exist"
fi
