#!/usr/bin/env bash
# this script configures an Ubuntu server with the below requirements

# make a temporary file
cp /etc/hosts ~/hosts.new
# this is for change the local host
sed -i '1 a 8.8.8.8  facebook.com' ~/hosts.new
# This is for change the facebook host
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
# move the hole information to the file
cp -f ~/hosts.new /etc/hosts
rm -f ~/hosts.new
